---

name: konstructs-client
version: git
summary: A voxel based game client
description: An open source Infiniminer/Minecraft inspired multiplayer game.
confinement: strict
grade: stable

apps:
  konstructs-client:
    command: desktop-launch $SNAP/konstructs-snap-wrapper
    plugs:
      - x11
      - network
      - opengl
      - unity7

parts:
  launcher:
    plugin: dump
    source: package
    snap: ["konstructs-snap-wrapper"]
  gui:
    plugin: nil
    after: [desktop-gtk3]
  client:
    plugin: cmake
    source: .
    configflags: [-DCMAKE_INSTALL_PREFIX=/]
    build-packages:
      - build-essential
      - xorg-dev
      - cmake
      - libx11-dev
      - zlib1g-dev
      - libgl1-mesa-dev
    stage-packages:
      - libgl1-mesa-dri
